# Generated by Django 5.0.4 on 2024-04-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_name', models.TextField(blank=True, db_column='name', null=True)),
                ('drug_id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'drug',
                'managed': False,
            },
        ),
    ]
