# Generated by Django 5.0.4 on 2024-04-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditionstype',
            fields=[
                ('con_type', models.TextField(blank=True, db_column='condition_name', null=True)),
                ('con_id', models.BigIntegerField(db_column='condition_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'condition_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pubmed',
            fields=[
                ('pmid', models.BigIntegerField(blank=True, db_column='PubMed ID', null=True)),
                ('drug_id', models.TextField(db_column='Abstract', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'references_data',
                'managed': False,
            },
        ),
    ]
