# Generated by Django 5.0.4 on 2024-04-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_conditionstype_pubmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brandtype',
            fields=[
                ('brand_name1', models.TextField(blank=True, db_column='brand_name1', null=True)),
                ('brand_name2', models.TextField(blank=True, db_column='brand_name2', null=True)),
                ('brand_name3', models.TextField(blank=True, db_column='brand_name3', null=True)),
                ('brand_id', models.BigIntegerField(db_column='brand_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'condition_type',
                'managed': False,
            },
        ),
    ]
